[package]
name = "collect_results"
version = "0.1.0"
authors = ["Ana Nora Evans <ananevans@gmail.com>"]

[dependencies]
results = { path = "../results" }
log = "0.4.5"
env_logger = "0.5.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.3"
