[package]
name = "hidden_unsafe_tests"
version = "0.1.0"
authors = ["Ana Nora Evans <ananevans@gmail.com>"]

[dependencies]
hidden_unsafe = { path = "/home/ans5k/work/external_calls/hidden_unsafe" }

