[package]
name = "hidden_unsafe"
version = "0.1.0"
authors = ["Ana Nora Evans <ananevans@gmail.com>"]

[lib]
name = "hidden_unsafe"
path = "src/lib.rs"
plugin = true

[dependencies]
chrono = "0.3"
cargo_metadata = "0.6.0"
cargo = "0.28.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
